{ provider: 'yahoo',
  id: 'HCGCNP6PTMTIAHQQDFGZOCOAMQ',
  displayName: 'Duke Pham',
  name: { familyName: 'Pham', givenName: 'Duke' },
  _raw: '{"profile":{"guid":"HCGCNP6PTMTIAHQQDFGZOCOAMQ","ageCategory":"A","created":"2016-08-07T01:18:47Z","emails":[{"handle":"dookpham@yahoo.com","id":1,"primary":true,"type":"HOME"}],"familyName":"Pham","gender":"UNSPECIFIED","givenName":"Duke","image":{"height":192,"imageUrl":"https://s.yimg.com/dh/ap/social/profile/profile_b192.png","size":"192x192","width":192},"intl":"us","jurisdiction":"us","lang":"en-US","memberSince":"2016-08-07T01:18:46Z","migrationSource":1,"nickname":"Duke","notStored":true,"nux":"3","phones":[{"id":10,"number":"1-4043172091","type":"MOBILE","verified":true}],"profileMode":"PUBLIC","profileStatus":"ACTIVE","profileUrl":"http://profile.yahoo.com/HCGCNP6PTMTIAHQQDFGZOCOAMQ","updated":"2016-08-07T01:18:47Z","isConnected":true,"profileHidden":false,"bdRestricted":true,"profilePermission":"PRIVATE","uri":"https://social.yahooapis.com/v1/user/HCGCNP6PTMTIAHQQDFGZOCOAMQ/profile","cache":true}}',
  _json: 
   { profile: 
      { guid: 'HCGCNP6PTMTIAHQQDFGZOCOAMQ',
        ageCategory: 'A',
        created: '2016-08-07T01:18:47Z',
        emails: [Object],
        familyName: 'Pham',
        gender: 'UNSPECIFIED',
        givenName: 'Duke',
        image: [Object],
        intl: 'us',
        jurisdiction: 'us',
        lang: 'en-US',
        memberSince: '2016-08-07T01:18:46Z',
        migrationSource: 1,
        nickname: 'Duke',
        notStored: true,
        nux: '3',
        phones: [Object],
        profileMode: 'PUBLIC',
        profileStatus: 'ACTIVE',
        profileUrl: 'http://profile.yahoo.com/HCGCNP6PTMTIAHQQDFGZOCOAMQ',
        updated: '2016-08-07T01:18:47Z',
        isConnected: true,
        profileHidden: false,
        bdRestricted: true,
        profilePermission: 'PRIVATE',
        uri: 'https://social.yahooapis.com/v1/user/HCGCNP6PTMTIAHQQDFGZOCOAMQ/profile',
        cache: true } },
  oauth_session_handle: 'ACyNpleodZnIXXNdzmEiyzV6LzDyxpASmxdlV5131GD0UnnYaZgXsBfDUheGUvDBxV2G4mCsI2LCmw.8' }